### ISSUE TITLE
Issue in bar chart with value `1`

### ISSUE THREAD

**Issue by nhoizey** [ffoodd/chaarts#111]
Here's a graph where the value `1` generates a bar larger than required, and moved below the label:

https://nicolas-hoizey.photo/stats/

![CleanShot 2023-10-30 at 16 16 23](https://github.com/ffoodd/chaarts/assets/78213/1704c65e-8d1f-4da3-9b28-9eac39796ca6)

**Comment by ffoodd** [comment]
Thanks for the bug report, it was a tricky one but since the first column in the grid is used for headers, a value starts at the second column — so setting a minimum value for `grid-column` did the trick.

**Comment by nhoizey** [comment]
It works indeed!
