### ISSUE TITLE
Bug on the pie demo page

### ISSUE THREAD

**Issue by GoOz** [ffoodd/chaarts#113]
I was browsing and stumbled upon a bug.

https://github.com/ffoodd/chaarts/assets/1280069/540b508b-1ae7-4296-abe1-beedc6b637c9

Can't see and reach the HTML bit with my mouse.

Also the tooltips on the sides are cropped but I'm guessing this is a size/overflow detail.

EDIT:
Forgot to specify my setup. :p
Firefox v124
MacOS 14.4.1

**Comment by ffoodd** [comment]
Thanks, I reproduce it on Ubuntu too. Not quite sure what's going on though :D

**Comment by GoOz** [comment]
@ffoodd I believe in you! :D
