### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by valentin-anamorphik** [ffoodd/chaarts#44]
Bonjour,

Peut-on animer les Column charts?

Merci.

**Comment by ffoodd** [comment]
Bonjour @valentin-anamorphik,

on ne peut pas animer les propriétés liées aux grilles (à ma connaissance), en revanche on peut imaginer animer le « remplissage » de l’arrière-plan avec `background-position`. C’est un sujet que je tenterai avec #5 — mais toute PR est bienvenue :)

**Comment by ffoodd** [comment]
Je ferme cette issue pour faire du ménage, mais c’est toujours un sujet considéré avec la #5 :)
