### ISSUE TITLE
Can't completely use decimal value with pie chart

### ISSUE THREAD

**Issue by GoOz** [ffoodd/chaarts#51]
If you use a decimal value (e.g. 23.33) to get a 23.33% percentage, the size of the share is well rendered but the content of the "tooltip" is wrong.

For my example, I had 3 values: 
- 20
- 56.67
- 23.33

And it's rendering like this (Chrome and Firefox had the same result).

https://user-images.githubusercontent.com/1280069/107249261-7b555b80-6a33-11eb-8aac-5507813741a7.mp4

I think it's because the `counter-reset` property just accepts integer.

I'm not sure there's any way to fix this or any workaround possible but It's good to know. I guess I'll just round the numbers then.

**Comment by ffoodd** [comment]
Thanks for the report, this is a very nice edge case :heart:

You'd be pleased to learn [there's a very simple way to convert a `<Number>` to an `<Integer>`](https://codepen.io/ffoodd/pen/xxRONQZ?editors=1100)—at least I was. The major drawback is rounding, but I guess it's better than `0` everywhere…

Expect this to be added very soon — but feel free to use it already.

If you do not support Firefox:
1. I don't love you anymore,
2. you may uncomment CSS comments, which works fine in Chromium-based browsers.

**Comment by GoOz** [comment]
Wow ok I didn't think of that. 😘

Of course I do support Firefox, who do you think I am? A frontend developer? :D
