### ISSUE TITLE
Little shifting issue on the Multiple Columns' striped background example

### ISSUE THREAD

**Issue by davidbgk** [ffoodd/chaarts#86]
<img width="1123" alt="Capture d’écran, le 2023-02-22 à 09 06 02" src="https://user-images.githubusercontent.com/3556/220645501-722cde32-2c11-414c-8cd1-2c129ca7c3d9.png">

Top is Chromium, bottom is Firefox, both have striped columns a bit shifted to the right compared to what I would expect.

Not sure how to fix that… yet!

**Comment by ffoodd** [comment]
Thanks for reporting, I'll need to check what may have changed.
